version: '3'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - frontend
    networks:
      - mynetwork

  frontend:
    build:
      context: ./templates
      dockerfile: Dockerfile_frontend
    ports:
      - "8080:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge