# Используем официальный образ Nginx
FROM nginx:latest

# Копируем файлы вашего фронтенда в папку с Nginx
COPY . /usr/share/nginx/html

# Открываем порт 80, который использует Nginx
EXPOSE 80

# Команда для запуска Nginx в фоновом режиме при старте контейнера
CMD ["nginx", "-g", "daemon off;"]